// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvEenLkxKkQv65d1dw96nO7poN0ZVX0Y',
    appId: '1:71990432098:web:a0e77d6713579431fa5c3b',
    messagingSenderId: '71990432098',
    projectId: 'authtutorial-d4422',
    authDomain: 'authtutorial-d4422.firebaseapp.com',
    storageBucket: 'authtutorial-d4422.appspot.com',
    measurementId: 'G-8XFDFXFPG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Q-3oLWTO2YGpOJGPh2ztEymq4M6erco',
    appId: '1:71990432098:android:8bb07f147b86d6eefa5c3b',
    messagingSenderId: '71990432098',
    projectId: 'authtutorial-d4422',
    storageBucket: 'authtutorial-d4422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUd4SegKoyEO6To3n_ildJVlMJoryb8I',
    appId: '1:71990432098:ios:8d25c412b93156a0fa5c3b',
    messagingSenderId: '71990432098',
    projectId: 'authtutorial-d4422',
    storageBucket: 'authtutorial-d4422.appspot.com',
    iosClientId:
        '71990432098-u3grio0k0mcfadr2ksat627oakdh6ena.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUd4SegKoyEO6To3n_ildJVlMJoryb8I',
    appId: '1:71990432098:ios:8d25c412b93156a0fa5c3b',
    messagingSenderId: '71990432098',
    projectId: 'authtutorial-d4422',
    storageBucket: 'authtutorial-d4422.appspot.com',
    iosClientId:
        '71990432098-u3grio0k0mcfadr2ksat627oakdh6ena.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
